openapi: 3.0.0
info:
  title: Travel Buddy Weather API
  version: 1.0.0
  description: API to fetch weather information for a given location.
servers:
  - url: https://travelbuddy.seaotterai.com/
paths:
  /weather/current:
    get:
      summary: Get current weather information for a specified location.
      operationId: getCurrentWeather
      parameters:
        - in: query
          name: location
          required: true
          schema:
            type: string
          description: The location name to fetch weather data for, e.g., "Seattle".
      responses:
        "200":
          description: Successful response with current weather and location details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  current:
                    type: object
                    properties:
                      cloud:
                        type: integer
                        example: 75
                      condition:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 1003
                          icon:
                            type: string
                            example: //cdn.weatherapi.com/weather/64x64/day/116.png
                          text:
                            type: string
                            example: Partly cloudy
                      feelslike_c:
                        type: number
                        format: float
                        example: 5.3
                      feelslike_f:
                        type: number
                        format: float
                        example: 41.6
                      gust_kph:
                        type: number
                        format: float
                        example: 12.2
                      gust_mph:
                        type: number
                        format: float
                        example: 7.6
                      humidity:
                        type: integer
                        example: 56
                      is_day:
                        type: integer
                        example: 1
                      last_updated:
                        type: string
                        example: 2024-02-26 15:00
                      last_updated_epoch:
                        type: integer
                        example: 1708988400
                      precip_in:
                        type: number
                        format: float
                        example: 0.02
                      precip_mm:
                        type: number
                        format: float
                        example: 0.63
                      pressure_in:
                        type: number
                        format: float
                        example: 29.84
                      pressure_mb:
                        type: number
                        format: float
                        example: 1011
                      temp_c:
                        type: number
                        format: float
                        example: 7.2
                      temp_f:
                        type: number
                        format: float
                        example: 45
                      uv:
                        type: number
                        format: float
                        example: 1
                      vis_km:
                        type: number
                        format: float
                        example: 16
                      vis_miles:
                        type: number
                        format: float
                        example: 9
                      wind_degree:
                        type: integer
                        example: 250
                      wind_dir:
                        type: string
                        example: WSW
                      wind_kph:
                        type: number
                        format: float
                        example: 9
                      wind_mph:
                        type: number
                        format: float
                        example: 5.6
                  location:
                    type: object
                    properties:
                      country:
                        type: string
                        example: United States of America
                      lat:
                        type: number
                        format: float
                        example: 47.61
                      localtime:
                        type: string
                        example: 2024-02-26 15:07
                      localtime_epoch:
                        type: integer
                        example: 1708988878
                      lon:
                        type: number
                        format: float
                        example: -122.33
                      name:
                        type: string
                        example: Seattle
                      region:
                        type: string
                        example: Washington
                      tz_id:
                        type: string
                        example: America/Los_Angeles
                required:
                  - current
                  - location
  /weather/forecast:
    get:
      summary: Get weather forecast
      operationId: getForecastWeather
      parameters:
        - in: query
          name: location
          required: true
          schema:
            type: string
          description: The location name for the weather forecast.
        - in: query
          name: days
          required: true
          schema:
            type: integer
          description: Number of days to forecast. Maximum is 14 days
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  current:
                    type: object
                    properties:
                      cloud:
                        type: integer
                      condition:
                        type: object
                        properties:
                          code:
                            type: integer
                          icon:
                            type: string
                          text:
                            type: string
                      feelslike_c:
                        type: number
                      feelslike_f:
                        type: number
                      gust_kph:
                        type: number
                      gust_mph:
                        type: number
                      humidity:
                        type: integer
                      is_day:
                        type: integer
                      last_updated:
                        type: string
                      last_updated_epoch:
                        type: integer
                      precip_in:
                        type: number
                      precip_mm:
                        type: number
                      pressure_in:
                        type: number
                      pressure_mb:
                        type: number
                      temp_c:
                        type: number
                      temp_f:
                        type: number
                      uv:
                        type: number
                      vis_km:
                        type: number
                      vis_miles:
                        type: number
                      wind_degree:
                        type: integer
                      wind_dir:
                        type: string
                      wind_kph:
                        type: number
                      wind_mph:
                        type: number
                  forecast:
                    type: object
                    properties:
                      forecastday:
                        type: array
                        items:
                          type: object
                          properties:
                            astro:
                              type: object
                              properties:
                                is_moon_up:
                                  type: integer
                                is_sun_up:
                                  type: integer
                                moon_illumination:
                                  type: integer
                                moon_phase:
                                  type: string
                                moonrise:
                                  type: string
                                moonset:
                                  type: string
                                sunrise:
                                  type: string
                                sunset:
                                  type: string
                            date:
                              type: string
                            date_epoch:
                              type: integer
                            day:
                              type: object
                              properties:
                                avghumidity:
                                  type: integer
                                avgtemp_c:
                                  type: number
                                avgtemp_f:
                                  type: number
                                avgvis_km:
                                  type: number
                                avgvis_miles:
                                  type: number
                                condition:
                                  type: object
                                  properties:
                                    code:
                                      type: integer
                                    icon:
                                      type: string
                                    text:
                                      type: string
                                daily_chance_of_rain:
                                  type: integer
                                daily_chance_of_snow:
                                  type: integer
                                daily_will_it_rain:
                                  type: integer
                                daily_will_it_snow:
                                  type: integer
                                maxtemp_c:
                                  type: number
                                maxtemp_f:
                                  type: number
                                maxwind_kph:
                                  type: number
                                maxwind_mph:
                                  type: number
                                mintemp_c:
                                  type: number
                                mintemp_f:
                                  type: number
                                totalprecip_in:
                                  type: number
                                totalprecip_mm:
                                  type: number
                                totalsnow_cm:
                                  type: number
                                uv:
                                  type: number
                            hour:
                              type: array
                              items:
                                type: object
                                properties:
                                  chance_of_rain:
                                    type: integer
                                  chance_of_snow:
                                    type: integer
                                  cloud:
                                    type: integer
                                  condition:
                                    type: object
                                    properties:
                                      code:
                                        type: integer
                                      icon:
                                        type: string
                                      text:
                                        type: string
                                  dewpoint_c:
                                    type: number
                                  dewpoint_f:
                                    type: number
                                  diff_rad:
                                    type: number
                                  feelslike_c:
                                    type: number
                                  feelslike_f:
                                    type: number
                                  gust_kph:
                                    type: number
                                  gust_mph:
                                    type: number
                                  heatindex_c:
                                    type: number
                                  heatindex_f:
                                    type: number
                                  humidity:
                                    type: integer
                                  is_day:
                                    type: integer
                                  precip_in:
                                    type: number
                                  precip_mm:
                                    type: number
                                  pressure_in:
                                    type: number
                                  pressure_mb:
                                    type: number
                                  short_rad:
                                    type: number
                                  snow_cm:
                                    type: number
                                  temp_c:
                                    type: number
                                  temp_f:
                                    type: number
                                  time:
                                    type: string
                                  time_epoch:
                                    type: integer
                                  uv:
                                    type: number
                                  vis_km:
                                    type: number
                                  vis_miles:
                                    type: number
                                  will_it_rain:
                                    type: integer
                                  will_it_snow:
                                    type: integer
                                  wind_degree:
                                    type: integer
                                  wind_dir:
                                    type: string
                                  wind_kph:
                                    type: number
                                  wind_mph:
                                    type: number
                                  windchill_c:
                                    type: number
                                  windchill_f:
                                    type: number
                  location:
                    type: object
                    properties:
                      country:
                        type: string
                      lat:
                        type: number
                      localtime:
                        type: string
                      localtime_epoch:
                        type: integer
                      lon:
                        type: number
                      name:
                        type: string
                      region:
                        type: string
                      tz_id:
                        type: string
  /place/find:
    get:
      summary: Find a place
      description: Fetches a place's Google Map URL based on the provided location text
      operationId: findPlaceOnGoogleMap
      parameters:
        - name: location
          in: query
          required: true
          schema:
            type: string
          description: The location text to query for Google Map URL
      responses:
        '200':
          description: Successful response with place details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  place_url:
                    type: string
                    example: "https://www.google.com/maps/place/?q=place_id:/?q=place_id:ChIJy0PC1XVyAHwRiEVSNmZ9_Qs"
  /place/reviews:
    get:
      summary: Find the customer reviews of a place
      description: Fetches a place's Google reviews on the provided location text
      operationId: findPlaceGoogleReview
      parameters:
        - name: location
          in: query
          required: True 
          schema:
            type: string
          description: The location text to query for Google Reviews
      responses:
        '200':
          description: Success response with google reviews of the place
          content:
            application/json:
              schema:
                type: object
                properties:
                  rating:
                    type: number 
                    example: 4.5
                  reviews:
                    type: object
                    properties:
                      text:
                        type: string
                        example: I love this place
                  user_rating_total:
                    type: number
                    example: 501
  /place/compute-routes:
    get:
      summary: Find travel distance and duration between two places
      description: Find the travel distance and how long it takes to travel between two places by driving
      operationId: findDirection
      parameters:
        - name: origin
          in: query
          required: True 
          schema:
            type: string 
          description: the origin location 
        - name: destination
          in: query 
          required: True 
          schema:
            type: string 
          description: the destination location
      responses:
        '200':
          description: Success response with distance and duration of two places travel by call
          content:
            application/json:
              schema:
                type: object
                properties:
                  distance:
                    type: string
                    example: 174 mile
                  duration:
                    type: string 
                    example: 1 hour
